/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES  */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Export de données de la table UserProfile : -1 rows
DELETE FROM "UserProfile";
/*!40000 ALTER TABLE "UserProfile" DISABLE KEYS */;
INSERT INTO "UserProfile" ("UserProfileId", "Name", "ProfileLevel", "SiteId", "CreatedDateTime", "ModifiedDateTime", "CreatedBy", "ModifiedBy") VALUES
	(1, 'Responsable', 2, 'MAR', NULL, NULL, NULL, NULL),
	(2, 'Garage', 1, 'MAR', NULL, NULL, NULL, NULL),
	(3, 'Administrateur', 4, 'MAR', NULL, NULL, NULL, NULL),
	(4, 'Compta', 3, 'MAR', NULL, NULL, NULL, NULL);
/*!40000 ALTER TABLE "UserProfile" ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
